/* Generated By:JJTree: Do not edit this line. ./CssParserTreeConstants.java */

package cz.vutbr.web.csskit.parser;

public interface CssParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTYLESHEET = 1;
  public int JJTIMPORT_A = 2;
  public int JJTMEDIA = 3;
  public int JJTMEDIUM = 4;
  public int JJTPAGE = 5;
  public int JJTPSEUDO_PAGE = 6;
  public int JJTOPERATOR = 7;
  public int JJTCOMBINATOR = 8;
  public int JJTUNARY_OPERATOR = 9;
  public int JJTPROPERTY = 10;
  public int JJTRULESET = 11;
  public int JJTSELECTOR = 12;
  public int JJTSIMPLE_SELECTOR = 13;
  public int JJTCLASS_A = 14;
  public int JJTELEMENT_NAME = 15;
  public int JJTATTRIB = 16;
  public int JJTPSEUDO = 17;
  public int JJTPFUNCTION = 18;
  public int JJTDECLARATION = 19;
  public int JJTPRIO = 20;
  public int JJTEXPR = 21;
  public int JJTTERM = 22;
  public int JJTFUNCTION = 23;
  public int JJTHEXCOLOR = 24;
  public int JJTCHARSET = 25;
  public int JJTEQUAL = 26;
  public int JJTINCLUDES = 27;
  public int JJTDASHMATCH = 28;
  public int JJTCOMMA = 29;
  public int JJTSLASH = 30;
  public int JJTHASH = 31;
  public int JJTIDENT = 32;
  public int JJTSTRING = 33;
  public int JJTURI = 34;
  public int JJTNUMBER = 35;
  public int JJTPERCENTAGE = 36;
  public int JJTLENGTHPX = 37;
  public int JJTLENGTHCM = 38;
  public int JJTLENGTHMM = 39;
  public int JJTLENGTHPT = 40;
  public int JJTLENGTHPC = 41;
  public int JJTEMS = 42;
  public int JJTEXS = 43;
  public int JJTANGLEDEG = 44;
  public int JJTANGLERAD = 45;
  public int JJTANGLEGRAD = 46;
  public int JJTTIMEMS = 47;
  public int JJTTIMES = 48;
  public int JJTFREQHZ = 49;
  public int JJTFREQKHZ = 50;
  public int JJTPLUS = 51;
  public int JJTMINUS = 52;
  public int JJTGREATER = 53;
  public int JJTFUNCTION_BEGIN = 54;


  public String[] jjtNodeName = {
    "start",
    "stylesheet",
    "import_a",
    "media",
    "medium",
    "page",
    "pseudo_page",
    "operator",
    "combinator",
    "unary_operator",
    "property",
    "ruleset",
    "selector",
    "simple_selector",
    "class_a",
    "element_name",
    "attrib",
    "pseudo",
    "pfunction",
    "declaration",
    "prio",
    "expr",
    "term",
    "function",
    "hexcolor",
    "charset",
    "equal",
    "includes",
    "dashmatch",
    "comma",
    "slash",
    "hash",
    "ident",
    "string",
    "uri",
    "number",
    "percentage",
    "lengthpx",
    "lengthcm",
    "lengthmm",
    "lengthpt",
    "lengthpc",
    "ems",
    "exs",
    "angledeg",
    "anglerad",
    "anglegrad",
    "timems",
    "times",
    "freqhz",
    "freqkhz",
    "plus",
    "minus",
    "greater",
    "function_begin",
  };
}
