/* Generated By:JJTree&JavaCC: Do not edit this line. CssParserConstants.java */
package cz.vutbr.web.cssKit.parser;

public interface CssParserConstants {

  int EOF = 0;
  int SLASH_STAR_COMMENT = 1;
  int h = 2;
  int nonascii = 3;
  int unicode = 4;
  int escape = 5;
  int nmstart = 6;
  int nmchar = 7;
  int string1 = 8;
  int string2 = 9;
  int invalid1 = 10;
  int invalid2 = 11;
  int comment = 12;
  int ident = 13;
  int name = 14;
  int num = 15;
  int string = 16;
  int invalid = 17;
  int url = 18;
  int ss = 19;
  int w = 20;
  int nl = 21;
  int A = 22;
  int C = 23;
  int D = 24;
  int E = 25;
  int G = 26;
  int H = 27;
  int I = 28;
  int K = 29;
  int M = 30;
  int N = 31;
  int O = 32;
  int P = 33;
  int R = 34;
  int S = 35;
  int T = 36;
  int X = 37;
  int Z = 38;
  int BLANK = 39;
  int CDO = 40;
  int CDC = 41;
  int EQUAL = 42;
  int INCLUDES = 43;
  int DASHMATCH = 44;
  int LBRACE = 45;
  int PLUS = 46;
  int MINUS = 47;
  int GREATER = 48;
  int COMMA = 49;
  int STRING = 50;
  int INVALID = 51;
  int IDENT = 52;
  int HASH = 53;
  int IMPORT_SYM = 54;
  int PAGE_SYM = 55;
  int MEDIA_SYM = 56;
  int CHARSET_SYM = 57;
  int IMPORTANT_SYM = 58;
  int EMS = 59;
  int EXS = 60;
  int LENGTHPX = 61;
  int LENGTHCM = 62;
  int LENGTHMM = 63;
  int LENGTHPT = 64;
  int LENGTHPC = 65;
  int ANGLEDEG = 66;
  int ANGLERAD = 67;
  int ANGLEGRAD = 68;
  int TIMEMS = 69;
  int TIMES = 70;
  int FREQHZ = 71;
  int FREQKHZ = 72;
  int DIMENSION = 73;
  int PERCENTAGE = 74;
  int NUMBER = 75;
  int URI = 76;
  int FUNCTION = 77;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SLASH_STAR_COMMENT>",
    "<h>",
    "<nonascii>",
    "<unicode>",
    "<escape>",
    "<nmstart>",
    "<nmchar>",
    "<string1>",
    "<string2>",
    "<invalid1>",
    "<invalid2>",
    "<comment>",
    "<ident>",
    "<name>",
    "<num>",
    "<string>",
    "<invalid>",
    "<url>",
    "<ss>",
    "<w>",
    "<nl>",
    "<A>",
    "<C>",
    "<D>",
    "<E>",
    "<G>",
    "<H>",
    "<I>",
    "<K>",
    "<M>",
    "<N>",
    "<O>",
    "<P>",
    "<R>",
    "<S>",
    "<T>",
    "<X>",
    "<Z>",
    "<BLANK>",
    "\"<!--\"",
    "\"-->\"",
    "\"=\"",
    "\"~=\"",
    "\"|=\"",
    "<LBRACE>",
    "<PLUS>",
    "<MINUS>",
    "<GREATER>",
    "<COMMA>",
    "<STRING>",
    "<INVALID>",
    "<IDENT>",
    "<HASH>",
    "<IMPORT_SYM>",
    "<PAGE_SYM>",
    "<MEDIA_SYM>",
    "<CHARSET_SYM>",
    "<IMPORTANT_SYM>",
    "<EMS>",
    "<EXS>",
    "<LENGTHPX>",
    "<LENGTHCM>",
    "<LENGTHMM>",
    "<LENGTHPT>",
    "<LENGTHPC>",
    "<ANGLEDEG>",
    "<ANGLERAD>",
    "<ANGLEGRAD>",
    "<TIMEMS>",
    "<TIMES>",
    "<FREQHZ>",
    "<FREQKHZ>",
    "<DIMENSION>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "<URI>",
    "<FUNCTION>",
    "\";\"",
    "\"}\"",
    "\":\"",
    "\".\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"/\"",
  };

}
